import type { ThemeTokens } from '../types/theme';

export const appleIosTheme: ThemeTokens = {
  id: 'apple-ios',
  name: 'Apple iOS',
  label: 'Apple',
  mode: 'light',
  colors: {
    background: '#F2F2F7',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    textPrimary: '#000000',
    textSecondary: 'rgba(60, 60, 67, 0.6)',
    textTertiary: 'rgba(60, 60, 67, 0.3)',
    accent: '#007AFF',
    accentSoft: 'rgba(0, 122, 255, 0.1)',
    border: 'transparent',
    divider: 'rgba(60, 60, 67, 0.12)',
    navActive: '#007AFF',
    navInactive: '#8E8E93',
    cardBg: '#FFFFFF',
    iconBg: '#E5E5EA',
    statusBar: '#000000',
    statusActive: '#007AFF',
    statusServed: '#34C759',
  },
  iconColors: {
    Towing: '#FF9500',
    Plumber: '#007AFF',
    HVAC: '#34C759',
    Electrician: '#FFCC00',
    'Lawn Care': '#30D158',
    Handyman: '#FF3B30',
    Roofing: '#5856D6',
    'Pest Control': '#AF52DE',
  },
  typography: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Helvetica Neue', sans-serif",
    fontFamilyHeading: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', sans-serif",
    headingSize: '34px',
    sectionSize: '22px',
    bodySize: '17px',
    captionSize: '13px',
    headingWeight: 700,
    sectionWeight: 700,
    bodyWeight: 400,
    letterSpacing: '-0.02em',
  },
  spacing: {
    screenPadding: '20px',
    sectionGap: '24px',
    gridGap: '0px',
    cardPadding: '16px',
    borderRadius: '13px',
    borderRadiusLg: '13px',
    iconSize: '24px',
    iconContainerSize: '40px',
  },
  iconStyle: {
    strokeWidth: 1.5,
    activeStrokeWidth: 2,
    fillActive: true,
  },
  chatInput: {
    placeholder: 'What do you need help with?',
    icon: 'sparkles',
    trailingIcon: 'none',
    heightOverride: '36px',
  },
  effects: {
    cardShadow: 'none',
  },
};
