import type { ThemeTokens } from '../types/theme';

export const claudeTheme: ThemeTokens = {
  id: 'claude',
  name: 'Claude',
  label: 'Claude',
  mode: 'light',
  colors: {
    background: '#FAF6F1',
    surface: '#FFFFFF',
    surfaceElevated: '#F5F0EB',
    textPrimary: '#1A1714',
    textSecondary: '#6B6560',
    textTertiary: '#9C9590',
    accent: '#C96442',
    accentSoft: 'rgba(201, 100, 66, 0.1)',
    border: '#E8E2DA',
    divider: '#E8E2DA',
    navActive: '#C96442',
    navInactive: '#9C9590',
    cardBg: '#FFFFFF',
    iconBg: '#F5F0EB',
    statusBar: '#1A1714',
    statusActive: '#C96442',
    statusServed: '#5A9A6E',
  },
  iconColors: {
    Towing: '#C96442',
    Plumber: '#3B7DC4',
    HVAC: '#5A9A6E',
    Electrician: '#D4A853',
    'Lawn Care': '#6B8F5E',
    Handyman: '#B85C3A',
    Roofing: '#7B6BA4',
    'Pest Control': '#9B7A5C',
  },
  typography: {
    fontFamily: "'DM Sans', sans-serif",
    fontFamilyHeading: "'Lora', serif",
    headingSize: '26px',
    sectionSize: '18px',
    bodySize: '15px',
    captionSize: '13px',
    headingWeight: 600,
    sectionWeight: 600,
    bodyWeight: 400,
    letterSpacing: '0em',
  },
  spacing: {
    screenPadding: '24px',
    sectionGap: '43px',
    gridGap: '14px',
    cardPadding: '18px',
    borderRadius: '12px',
    borderRadiusLg: '12px',
    iconSize: '24px',
    iconContainerSize: '56px',
  },
  iconStyle: {
    strokeWidth: 1.4,
    activeStrokeWidth: 1.8,
    fillActive: false,
  },
  chatInput: {
    placeholder: 'Describe what you need...',
    icon: 'messageCircle',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: '0 1px 4px rgba(26, 23, 20, 0.06)',
  },
};
