import type { ThemeTokens } from '../types/theme';

export const materialYouTheme: ThemeTokens = {
  id: 'material-you',
  name: 'Material You',
  label: 'Google',
  mode: 'light',
  colors: {
    background: '#FEF7FF',
    surface: '#F3EDF7',
    surfaceElevated: '#EADDFF',
    textPrimary: '#1D1B20',
    textSecondary: '#49454F',
    textTertiary: '#79747E',
    accent: '#6750A4',
    accentSoft: '#E8DEF8',
    border: 'transparent',
    divider: '#CAC4D0',
    navActive: '#6750A4',
    navInactive: '#49454F',
    cardBg: '#FFFBFE',
    iconBg: '#E8DEF8',
    statusBar: '#1D1B20',
    statusActive: '#6750A4',
    statusServed: '#1D6B35',
  },
  typography: {
    fontFamily: "'Roboto', sans-serif",
    fontFamilyHeading: "'Plus Jakarta Sans', sans-serif",
    headingSize: '28px',
    sectionSize: '22px',
    bodySize: '14px',
    captionSize: '12px',
    headingWeight: 400,
    sectionWeight: 500,
    bodyWeight: 400,
    letterSpacing: '0.01em',
  },
  spacing: {
    screenPadding: '24px',
    sectionGap: '12px',
    gridGap: '16px',
    cardPadding: '20px',
    borderRadius: '28px',
    borderRadiusLg: '28px',
    iconSize: '24px',
    iconContainerSize: '64px',
  },
  iconStyle: {
    strokeWidth: 2,
    activeStrokeWidth: 2,
    fillActive: true,
  },
  chatInput: {
    placeholder: 'Ask your Genie anything...',
    icon: 'sparkles',
    trailingIcon: 'mic',
    heightOverride: '56px',
  },
  effects: {
    cardShadow: '0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.06)',
  },
};
