import type { ThemeTokens } from '../types/theme';

export const premiumTheme: ThemeTokens = {
  id: 'premium',
  name: 'Current',
  label: 'Current',
  mode: 'dark',
  colors: {
    background: '#050505',
    surface: '#121212',
    surfaceElevated: '#1A1A1A',
    textPrimary: '#EDEDED',
    textSecondary: '#A1A1A1',
    textTertiary: '#666666',
    accent: '#FF4D00',
    accentSoft: 'rgba(255, 77, 0, 0.15)',
    border: '#333333',
    divider: '#333333',
    navActive: '#FF4D00',
    navInactive: '#666666',
    cardBg: '#121212',
    iconBg: '#1A1A1A',
    statusBar: '#EDEDED',
    statusActive: '#FF4D00',
    statusServed: '#00E096',
  },
  iconColors: {
    Towing: '#FF4D00',
    Plumber: '#2E93FA',
    HVAC: '#00E096',
    Electrician: '#FFC043',
    'Lawn Care': '#00E096',
    Handyman: '#FF6A2B',
    Roofing: '#A1A1A1',
    'Pest Control': '#FF2D55',
  },
  typography: {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontFamilyHeading: "'Outfit', sans-serif",
    headingSize: '32px',
    sectionSize: '20px',
    bodySize: '16px',
    captionSize: '12px',
    headingWeight: 600,
    sectionWeight: 500,
    bodyWeight: 400,
    letterSpacing: '-0.01em',
  },
  spacing: {
    screenPadding: '24px',
    sectionGap: '34px',
    gridGap: '16px',
    cardPadding: '16px',
    borderRadius: '12px',
    borderRadiusLg: '24px',
    iconSize: '24px',
    iconContainerSize: '52px',
  },
  iconStyle: {
    strokeWidth: 2.0,
    activeStrokeWidth: 2.5,
    fillActive: true,
  },
  chatInput: {
    placeholder: 'Enter Query...',
    icon: 'search',
    trailingIcon: 'arrowUp',
  },
  effects: {
    glass: false,
    cardShadow: 'none',
  },
};
