import type { ThemeTokens } from '../types/theme';

export const uberSignalTheme: ThemeTokens = {
  id: 'uber-signal',
  name: 'Signal',
  label: 'Signal',
  mode: 'dark',
  colors: {
    background: '#0C0C0C',
    surface: '#181818',
    surfaceElevated: '#222222',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A0A0',
    textTertiary: '#606060',
    accent: '#00D4AA',
    accentSoft: 'rgba(0, 212, 170, 0.10)',
    border: '#2A2A2A',
    divider: '#222222',
    navActive: '#00D4AA',
    navInactive: '#555555',
    cardBg: '#181818',
    iconBg: 'transparent',
    statusBar: '#FFFFFF',
    ctaGreen: '#00D4AA',
    statusActive: '#00D4AA',
    statusServed: '#00D4AA',
  },
  iconColors: {
    Towing: '#FFFFFF',
    Plumber: '#FFFFFF',
    HVAC: '#FFFFFF',
    Electrician: '#FFFFFF',
    'Lawn Care': '#FFFFFF',
    Handyman: '#FFFFFF',
    Roofing: '#FFFFFF',
    'Pest Control': '#FFFFFF',
  },
  typography: {
    fontFamily: "'Inter', sans-serif",
    fontFamilyHeading: "'Bebas Neue', sans-serif",
    headingSize: '40px',
    sectionSize: '24px',
    bodySize: '14px',
    captionSize: '11px',
    headingWeight: 400,
    sectionWeight: 400,
    bodyWeight: 400,
    letterSpacing: '0.04em',
  },
  spacing: {
    screenPadding: '16px',
    sectionGap: '20px',
    gridGap: '8px',
    cardPadding: '20px',
    borderRadius: '8px',
    borderRadiusLg: '20px',
    iconSize: '72px',
    iconContainerSize: '72px',
  },
  iconStyle: {
    strokeWidth: 1.5,
    activeStrokeWidth: 2,
    fillActive: false,
  },
  chatInput: {
    placeholder: "What's broken?",
    icon: 'messageCircle',
    trailingIcon: 'mic',
  },
  effects: {
    cardShadow: 'none',
  },
  layout: {
    suggestionsStyle: 'pill-categories',
    activityStyle: 'minimal',
    headerStyle: 'hero',
  },
  serviceIconStyle: 'gradient-outlined',
};
