import type { ThemeTokens } from '../types/theme';

export const uberAuraTheme: ThemeTokens = {
  id: 'uber-aura',
  name: 'Aura',
  label: 'Aura',
  mode: 'dark',
  colors: {
    background: '#0A0A0A',
    surface: '#111111',
    surfaceElevated: '#171717',
    textPrimary: '#F5F0EB',
    textSecondary: '#8A8580',
    textTertiary: '#4A4744',
    accent: '#C9A96E',
    accentSoft: 'rgba(201, 169, 110, 0.08)',
    border: 'rgba(201, 169, 110, 0.12)',
    divider: 'rgba(201, 169, 110, 0.06)',
    navActive: '#C9A96E',
    navInactive: '#4A4744',
    cardBg: '#111111',
    iconBg: 'transparent',
    statusBar: '#FFFFFF',
    ctaGreen: '#C9A96E',
    statusActive: '#C9A96E',
    statusServed: '#4ADE80',
  },
  iconColors: {
    Towing: '#C9A96E',
    Plumber: '#7CA8C9',
    HVAC: '#6DB8A0',
    Electrician: '#D4B872',
    'Lawn Care': '#7AB88A',
    Handyman: '#A89BC9',
    Roofing: '#C9956E',
    'Pest Control': '#C97E8A',
  },
  typography: {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    headingSize: '28px',
    sectionSize: '14px',
    bodySize: '15px',
    captionSize: '12px',
    headingWeight: 600,
    sectionWeight: 500,
    bodyWeight: 400,
    letterSpacing: '-0.01em',
  },
  spacing: {
    screenPadding: '24px',
    sectionGap: '43px',
    gridGap: '8px',
    cardPadding: '16px',
    borderRadius: '12px',
    borderRadiusLg: '16px',
    iconSize: '20px',
    iconContainerSize: '40px',
  },
  iconStyle: {
    strokeWidth: 1.5,
    activeStrokeWidth: 2,
    fillActive: true,
  },
  chatInput: {
    placeholder: 'Ask anything...',
    icon: 'sparkles',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: '0 2px 16px rgba(201, 169, 110, 0.04), 0 0 1px rgba(201, 169, 110, 0.1)',
  },
  layout: {
    suggestionsStyle: 'floating-cards',
    activityStyle: 'card',
    headerStyle: 'standard',
  },
  serviceIconStyle: 'unicons',
};
