import type { ThemeTokens } from '../types/theme';

export const uberMatrixTheme: ThemeTokens = {
  id: 'uber-matrix',
  name: 'Matrix',
  label: 'Matrix',
  mode: 'dark',
  colors: {
    background: '#0C0C10',
    surface: '#16161C',
    surfaceElevated: '#1E1E26',
    textPrimary: '#E8E8F0',
    textSecondary: '#9898A8',
    textTertiary: '#5C5C6B',
    accent: '#A78BFA',
    accentSoft: 'rgba(167, 139, 250, 0.08)',
    border: '#2A2A36',
    divider: '#202028',
    navActive: '#A78BFA',
    navInactive: '#5C5C6B',
    cardBg: '#16161C',
    iconBg: 'rgba(167, 139, 250, 0.06)',
    statusBar: '#FFFFFF',
    ctaGreen: '#A78BFA',
    statusActive: '#A78BFA',
    statusServed: '#4ADE80',
  },
  iconColors: {
    Towing: '#F97316',
    Plumber: '#38BDF8',
    HVAC: '#34D399',
    Electrician: '#FBBF24',
    'Lawn Care': '#4ADE80',
    Handyman: '#A78BFA',
    Roofing: '#FB923C',
    'Pest Control': '#F472B6',
  },
  typography: {
    fontFamily: "'Inter', sans-serif",
    fontFamilyHeading: "'Space Grotesk', sans-serif",
    headingSize: '24px',
    sectionSize: '13px',
    bodySize: '13px',
    captionSize: '11px',
    headingWeight: 600,
    sectionWeight: 600,
    bodyWeight: 400,
    letterSpacing: '-0.01em',
  },
  spacing: {
    screenPadding: '16px',
    sectionGap: '27px',
    gridGap: '8px',
    cardPadding: '12px',
    borderRadius: '8px',
    borderRadiusLg: '12px',
    iconSize: '22px',
    iconContainerSize: '36px',
  },
  iconStyle: {
    strokeWidth: 1.5,
    activeStrokeWidth: 2,
    fillActive: false,
  },
  chatInput: {
    placeholder: 'Search services...',
    icon: 'search',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: 'none',
  },
  layout: {
    suggestionsStyle: 'compact-tile-grid',
    activityStyle: 'card',
    headerStyle: 'compact',
  },
  serviceIconStyle: 'unicons',
};
