import type { ThemeTokens } from '../types/theme';

export const uberTheme: ThemeTokens = {
  id: 'uber',
  name: 'Uber',
  label: 'Uber',
  mode: 'dark',
  colors: {
    background: '#000000',
    surface: '#141414',
    surfaceElevated: '#1F1F1F',
    textPrimary: '#FFFFFF',
    textSecondary: '#ABABAB',
    textTertiary: '#6B6B6B',
    accent: '#FFFFFF',
    accentSoft: 'rgba(255, 255, 255, 0.08)',
    border: '#2A2A2A',
    divider: '#2A2A2A',
    navActive: '#FFFFFF',
    navInactive: '#6B6B6B',
    cardBg: '#141414',
    iconBg: '#1F1F1F',
    statusBar: '#FFFFFF',
    ctaGreen: '#06C167',
    statusActive: '#FFFFFF',
    statusServed: '#06C167',
  },
  iconColors: {
    Towing: '#FFFFFF',
    Plumber: '#FFFFFF',
    HVAC: '#FFFFFF',
    Electrician: '#FFFFFF',
    'Lawn Care': '#FFFFFF',
    Handyman: '#FFFFFF',
    Roofing: '#FFFFFF',
    'Pest Control': '#FFFFFF',
  },
  typography: {
    fontFamily: "'DM Sans', sans-serif",
    headingSize: '32px',
    sectionSize: '20px',
    bodySize: '14px',
    captionSize: '12px',
    headingWeight: 700,
    sectionWeight: 700,
    bodyWeight: 500,
    letterSpacing: '-0.02em',
  },
  spacing: {
    screenPadding: '16px',
    sectionGap: '24px',
    gridGap: '12px',
    cardPadding: '16px',
    borderRadius: '8px',
    borderRadiusLg: '8px',
    iconSize: '24px',
    iconContainerSize: '52px',
  },
  iconStyle: {
    strokeWidth: 2.2,
    activeStrokeWidth: 2.4,
    fillActive: false,
  },
  chatInput: {
    placeholder: 'Where do you need help?',
    icon: 'search',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: 'none',
  },
};
