import type { ThemeTokens } from '../types/theme';

export const uberNightrideTheme: ThemeTokens = {
  id: 'uber-nightride',
  name: 'Nightride',
  label: 'Nightride',
  mode: 'dark',
  colors: {
    background: '#0A0A0A',
    surface: '#161616',
    surfaceElevated: '#1E1E1E',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A0A0',
    textTertiary: '#5C5C5C',
    accent: '#FFFFFF',
    accentSoft: 'rgba(255,255,255,0.06)',
    border: '#262626',
    divider: '#262626',
    navActive: '#FFFFFF',
    navInactive: '#5C5C5C',
    cardBg: '#161616',
    iconBg: 'transparent',
    statusBar: '#FFFFFF',
    ctaGreen: '#276EF1',
    statusActive: '#276EF1',
    statusServed: '#06C167',
  },
  iconColors: {
    Towing: '#FF6B6B',
    Plumber: '#4DABF7',
    HVAC: '#51CF66',
    Electrician: '#FFD43B',
    'Lawn Care': '#69DB7C',
    Handyman: '#FF922B',
    Roofing: '#ADB5BD',
    'Pest Control': '#CC5DE8',
  },
  typography: {
    fontFamily: "'Inter', sans-serif",
    fontFamilyHeading: "'Space Grotesk', sans-serif",
    headingSize: '30px',
    sectionSize: '18px',
    bodySize: '14px',
    captionSize: '12px',
    headingWeight: 600,
    sectionWeight: 600,
    bodyWeight: 400,
    letterSpacing: '-0.03em',
  },
  spacing: {
    screenPadding: '20px',
    sectionGap: '34px',
    gridGap: '12px',
    cardPadding: '16px',
    borderRadius: '14px',
    borderRadiusLg: '20px',
    iconSize: '64px',
    iconContainerSize: '136px',
  },
  iconStyle: {
    strokeWidth: 1.8,
    activeStrokeWidth: 2,
    fillActive: false,
  },
  chatInput: {
    placeholder: 'What do you need?',
    icon: 'search',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: '0 2px 12px rgba(0,0,0,0.4)',
  },
  layout: {
    suggestionsStyle: 'horizontal-scroll',
    suggestionCardHeight: '180px',
    activityStyle: 'timeline',
    headerStyle: 'standard',
  },
  serviceIconStyle: '3d-glossy',
};
