import type { ThemeTokens } from '../types/theme';

export const uberMonoTheme: ThemeTokens = {
  id: 'uber-mono',
  name: 'Mono',
  label: 'Mono',
  mode: 'dark',
  colors: {
    background: '#0D0D0D',
    surface: '#161616',
    surfaceElevated: '#1A1A1A',
    textPrimary: '#E0E0E0',
    textSecondary: '#888888',
    textTertiary: '#555555',
    accent: '#00FF88',
    accentSoft: 'rgba(0, 255, 136, 0.08)',
    border: '#2A2A2A',
    divider: '#222222',
    navActive: '#00FF88',
    navInactive: '#555555',
    cardBg: '#161616',
    iconBg: 'transparent',
    statusBar: '#FFFFFF',
    ctaGreen: '#00FF88',
    statusActive: '#00FF88',
    statusServed: '#00FF88',
  },
  iconColors: {
    Towing: '#E0E0E0',
    Plumber: '#E0E0E0',
    HVAC: '#E0E0E0',
    Electrician: '#E0E0E0',
    'Lawn Care': '#E0E0E0',
    Handyman: '#E0E0E0',
    Roofing: '#E0E0E0',
    'Pest Control': '#E0E0E0',
  },
  typography: {
    fontFamily: "'JetBrains Mono', monospace",
    headingSize: '22px',
    sectionSize: '13px',
    bodySize: '14px',
    captionSize: '11px',
    headingWeight: 700,
    sectionWeight: 600,
    bodyWeight: 400,
    letterSpacing: '0em',
  },
  spacing: {
    screenPadding: '16px',
    sectionGap: '44px',
    gridGap: '2px',
    cardPadding: '12px',
    borderRadius: '4px',
    borderRadiusLg: '4px',
    iconSize: '28px',
    iconContainerSize: '28px',
  },
  iconStyle: {
    strokeWidth: 1.5,
    activeStrokeWidth: 2,
    fillActive: false,
  },
  chatInput: {
    placeholder: 'query.new',
    icon: 'messageCircle',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: 'none',
  },
  layout: {
    suggestionsStyle: 'vertical-stack',
    activityStyle: 'minimal',
    headerStyle: 'compact',
  },
  serviceIconStyle: '3d-isometric',
};
