import type { ThemeTokens } from '../types/theme';

export const uberDashTheme: ThemeTokens = {
  id: 'uber-dash',
  name: 'Dash',
  label: 'Dash',
  mode: 'dark',
  colors: {
    background: '#080808',
    surface: '#141414',
    surfaceElevated: '#1C1C1C',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A0A0',
    textTertiary: '#5C5C5C',
    accent: '#FF6B35',
    accentSoft: 'rgba(255, 107, 53, 0.1)',
    border: '#262626',
    divider: '#1E1E1E',
    navActive: '#FF6B35',
    navInactive: '#5C5C5C',
    cardBg: '#141414',
    iconBg: 'rgba(255, 107, 53, 0.08)',
    statusBar: '#FFFFFF',
    ctaGreen: '#FF6B35',
    statusActive: '#FF6B35',
    statusServed: '#06C167',
  },
  iconColors: {
    Towing: '#FF6B35',
    Plumber: '#4DA8FF',
    HVAC: '#00D4AA',
    Electrician: '#FFD60A',
    'Lawn Care': '#34D399',
    Handyman: '#A78BFA',
    Roofing: '#F97316',
    'Pest Control': '#FB7185',
  },
  typography: {
    fontFamily: "'Inter', sans-serif",
    fontFamilyHeading: "'DM Sans', sans-serif",
    headingSize: '26px',
    sectionSize: '15px',
    bodySize: '14px',
    captionSize: '12px',
    headingWeight: 700,
    sectionWeight: 600,
    bodyWeight: 400,
    letterSpacing: '-0.02em',
  },
  spacing: {
    screenPadding: '20px',
    sectionGap: '24px',
    gridGap: '10px',
    cardPadding: '14px',
    borderRadius: '20px',
    borderRadiusLg: '24px',
    iconSize: '18px',
    iconContainerSize: '32px',
  },
  iconStyle: {
    strokeWidth: 1.5,
    activeStrokeWidth: 2,
    fillActive: true,
  },
  chatInput: {
    placeholder: 'What do you need?',
    icon: 'sparkles',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: 'none',
  },
  layout: {
    suggestionsStyle: 'chip-rows',
    activityStyle: 'minimal',
    headerStyle: 'standard',
  },
  serviceIconStyle: 'unicons',
};
