import type { ThemeTokens } from '../types/theme';

export const uberSoftTheme: ThemeTokens = {
  id: 'uber-soft',
  name: 'Soft',
  label: 'Soft',
  mode: 'dark',
  colors: {
    background: '#121218',
    surface: '#1C1C24',
    surfaceElevated: '#242430',
    textPrimary: '#F0F0F5',
    textSecondary: '#9898A8',
    textTertiary: '#5C5C6B',
    accent: '#7B61FF',
    accentSoft: 'rgba(123, 97, 255, 0.10)',
    border: '#2A2A35',
    divider: '#2A2A35',
    navActive: '#7B61FF',
    navInactive: '#5C5C6B',
    cardBg: '#1C1C24',
    iconBg: 'transparent',
    statusBar: '#FFFFFF',
    ctaGreen: '#7B61FF',
    statusActive: '#7B61FF',
    statusServed: '#4ADE80',
  },
  iconColors: {
    Towing: '#FF7B7B',
    Plumber: '#64B5F6',
    HVAC: '#81C784',
    Electrician: '#FFD54F',
    'Lawn Care': '#A5D6A7',
    Handyman: '#FFB74D',
    Roofing: '#B0BEC5',
    'Pest Control': '#CE93D8',
  },
  typography: {
    fontFamily: "'Nunito Sans', sans-serif",
    fontFamilyHeading: "'Nunito', sans-serif",
    headingSize: '34px',
    sectionSize: '18px',
    bodySize: '14px',
    captionSize: '12px',
    headingWeight: 700,
    sectionWeight: 700,
    bodyWeight: 400,
    letterSpacing: '-0.01em',
  },
  spacing: {
    screenPadding: '16px',
    sectionGap: '18px',
    gridGap: '12px',
    cardPadding: '16px',
    borderRadius: '20px',
    borderRadiusLg: '28px',
    iconSize: '52px',
    iconContainerSize: '56px',
  },
  iconStyle: {
    strokeWidth: 1.8,
    activeStrokeWidth: 2,
    fillActive: false,
  },
  chatInput: {
    placeholder: 'Tell me what you need...',
    icon: 'sparkles',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: '0 4px 20px rgba(123, 97, 255, 0.06), 0 1px 4px rgba(0, 0, 0, 0.2)',
  },
  layout: {
    suggestionsStyle: 'bento',
    activityStyle: 'card',
    headerStyle: 'hero',
  },
  serviceIconStyle: '3d-clay',
};
