import type { ThemeTokens } from '../types/theme';

export const uberGridTheme: ThemeTokens = {
  id: 'uber-grid',
  name: 'Grid',
  label: 'Grid',
  mode: 'dark',
  colors: {
    background: '#000000',
    surface: '#141414',
    surfaceElevated: '#1A1A1A',
    textPrimary: '#FFFFFF',
    textSecondary: '#999999',
    textTertiary: '#616161',
    accent: '#FFFFFF',
    accentSoft: 'rgba(255,255,255,0.06)',
    border: '#222222',
    divider: '#1E1E1E',
    navActive: '#FFFFFF',
    navInactive: '#5C5C5C',
    cardBg: '#141414',
    iconBg: 'transparent',
    statusBar: '#FFFFFF',
    ctaGreen: '#06C167',
    statusActive: '#FFFFFF',
    statusServed: '#06C167',
  },
  iconColors: {
    Towing: '#FF6B6B',
    Plumber: '#4DABF7',
    HVAC: '#51CF66',
    Electrician: '#FFD43B',
    'Lawn Care': '#69DB7C',
    Handyman: '#FF922B',
    Roofing: '#ADB5BD',
    'Pest Control': '#CC5DE8',
  },
  typography: {
    fontFamily: "'DM Sans', sans-serif",
    headingSize: '28px',
    sectionSize: '16px',
    bodySize: '13px',
    captionSize: '11px',
    headingWeight: 800,
    sectionWeight: 700,
    bodyWeight: 500,
    letterSpacing: '-0.01em',
  },
  spacing: {
    screenPadding: '16px',
    sectionGap: '18px',
    gridGap: '10px',
    cardPadding: '14px',
    borderRadius: '12px',
    borderRadiusLg: '16px',
    iconSize: '48px',
    iconContainerSize: '175px',
  },
  iconStyle: {
    strokeWidth: 2.2,
    activeStrokeWidth: 2.4,
    fillActive: false,
  },
  chatInput: {
    placeholder: 'Describe your problem',
    icon: 'messageCircle',
    trailingIcon: 'arrowUp',
  },
  effects: {
    cardShadow: 'none',
  },
  layout: {
    suggestionsStyle: 'grid-2col',
    suggestionCardHeight: '140px',
    activityStyle: 'minimal',
    headerStyle: 'compact',
  },
  serviceIconStyle: 'flat-vivid',
  serviceSubtitles: {
    Towing: '2.1 mi away',
    Plumber: '1.4 mi away',
    HVAC: '3 available',
    Electrician: '5 available',
    'Lawn Care': 'Top rated',
    Handyman: 'Last used 3d ago',
    Roofing: '2.8 mi away',
    'Pest Control': '4 available',
  },
};
